### ISSUE TITLE
Inquiry About Code Implementation for Generating Text Embeddings from Vocabulary Set Using CLIP Text Encoder

### ISSUE THREAD

**Issue by c1ircle** [fanghaook/OVFormer#1]
Thank you for your excellent work! 
While studying the code, I noticed you feed the vocabulary set into the CLIP text encoder to generate the text embedding as the category labels. However, I couldn't find the corresponding code. Could you please point out the specific code for this? Thank you very much!

**Comment by fanghaook** [comment]
Like [LVVIS](https://github.com/haochenheheda/LVVIS), we saved the text embeddings in advance to the local folder metadata, and did not use CLIP text encoder during model training and testing. You can see [here](https://github.com/fanghaook/OVFormer/blob/master/datasets/README.md#step-2-prepare-metadata) for details.

**Comment by c1ircle** [comment]
Thank you so much for taking the time to explain this! The issue is now resolved, thanks again!
