### ISSUE TITLE
Problems about the Unified Embedding alignment

### ISSUE THREAD

**Issue by yahooo-m** [fanghaook/OVFormer#2]
Hi, great job. While debugging the code, I couldn't find this module. Is the "outputs_class = self.class_embed(decoder_output, features_clip)" in forward_prediction_head the module you are referring to?

**Comment by fanghaook** [comment]
[`self.class_embed = ZeroShotClassifier(256, num_classes, self.clip_text_path)`](https://github.com/fanghaook/OVFormer/blob/d6fc6829e3da2ab8e318982633694416295fcd4c/ovformer/modeling/transformer_decoder/mask2former_transformer_decoder.py#L341)
We perform unified embedding alignment in [`ZeroShotClassifier`](https://github.com/fanghaook/OVFormer/blob/d6fc6829e3da2ab8e318982633694416295fcd4c/ovformer/modeling/transformer_decoder/zero_shot_classifier.py)

**Comment by yahooo-m** [comment]
Thanks. I find it.
